# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\draft1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette
from PyQt5.QtWidgets import *
from KeyWatcher import KeyWatcher
from win32gui import PumpMessages
from KeyListWidget import KeyListWidget
from Hotkeys import Hotkeys


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 412)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.listWidget = KeyListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(50, 70, 881, 301))
        self.listWidget.setObjectName("listWidget")

        self.curentTime = QtWidgets.QLCDNumber(self.centralwidget)
        self.curentTime.setGeometry(QtCore.QRect(120, 30, 121, 23))
        self.curentTime.setObjectName("curentTime")
        self.diffTime = QtWidgets.QLCDNumber(self.centralwidget)
        self.diffTime.setGeometry(QtCore.QRect(280, 30, 121, 23))
        self.diffTime.setObjectName("diffTime")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(650, 30, 30, 30))
        self.addButton.setStyleSheet("image: url(:/images/images/plus.png);\n"
"padding:3px;")
        self.addButton.setText("")
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(750, 30, 30, 30))
        self.deleteButton.setStyleSheet("image: url(:/images/images/undo.png);\n"
"padding: 4px;")
        self.deleteButton.setText("")
        self.deleteButton.setObjectName("deleteButton")
        self.undoButton = QtWidgets.QPushButton(self.centralwidget)
        self.undoButton.setGeometry(QtCore.QRect(800, 30, 30, 30))
        self.undoButton.setStyleSheet("image: url(:/images/images/redo.png);\n"
"padding: 4px;")
        self.undoButton.setText("")
        self.undoButton.setObjectName("undoButton")
        self.configButton = QtWidgets.QPushButton(self.centralwidget)
        self.configButton.setGeometry(QtCore.QRect(900, 30, 30, 30))
        self.configButton.setStyleSheet("image: url(:/images/images/settings.png);\n"
"padding: 3px;")
        self.configButton.setText("")
        self.configButton.setObjectName("configButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(700, 30, 30, 30))
        self.saveButton.setStyleSheet("image: url(:/images/images/minus.png);\n"
"padding: 4px;")
        self.saveButton.setText("")
        self.saveButton.setObjectName("saveButton")
        self.redoButton = QtWidgets.QPushButton(self.centralwidget)
        self.redoButton.setGeometry(QtCore.QRect(850, 30, 30, 30))
        self.redoButton.setStyleSheet("image: url(:/images/images/save.png);\n"
"padding: 4px;")
        self.redoButton.setText("")
        self.redoButton.setObjectName("redoButton")
        self.totalTime = QtWidgets.QLCDNumber(self.centralwidget)
        self.totalTime.setGeometry(QtCore.QRect(440, 30, 121, 23))
        self.totalTime.setObjectName("totalTime")

        self.recordButton = QtWidgets.QPushButton(self.centralwidget)
        self.recordButton.setGeometry(QtCore.QRect(600, 30, 30, 30))
        self.recordButton.setStyleSheet("padding:5px;\n"
"image: url(:/images/images/record.png);")
        self.recordButton.setText("")
        self.recordButton.setObjectName("recordButton")
        self.recordButton.setCheckable(True)

        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(50, 30, 30, 30))
        self.backButton.setStyleSheet("padding:3px;\n"
"image: url(:/images/images/back.png);")
        self.backButton.setText("")
        self.backButton.setObjectName("backButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))   

import qtresources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    #temp
    watcher = KeyWatcher(ui.listWidget, ui.totalTime)
    hotkeyRecorder = Hotkeys(watcher)
    ui.recordButton.toggled.connect(watcher.toggleRecord)
    ui.backButton.clicked.connect(
            lambda: ui.listWidget.reloadMacroList(hotkeyRecorder))
    ui.backButton.clicked.connect(watcher.onBack)

    # lmao what is this line
    ui.addButton.clicked.connect(
            lambda: ui.listWidget.listWidgetAddEditLabel(
            hotkeyRecorder, 'untitled'))
    #ui.undoButton.clicked.connect(watcher.runMacro)
    #PumpMessages()

    sys.exit(app.exec_())
