# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from pyHook import HookManager
from pyHook import HookConstants
from win32gui import PumpMessages, PostQuitMessage
from pprint import pprint

class Keystroke_Watcher(object):
    def __init__(self, wind):
        self.hm = HookManager()
        self.hm.KeyDown = self.on_keyboard_event
        self.hm.KeyUp = self.on_key_up_event
        self.hm.HookKeyboard()
        self.wind = wind

    def on_key_up_event(self, event):
        print(event.KeyID)
        return True

    def on_keyboard_event(self, event):
        print(event.KeyID)
        self.wind.model.appendRow(QtGui.QStandardItem(chr(event.KeyID)))
        try:
            if event.KeyID  == ord('E'):
                self.your_method()
        finally:
            return True

    def your_method(self):
        self.new_wind = SubWindow()
        self.new_wind.show()

    def shutdown(self):
        PostQuitMessage(0)
        self.hm.UnhookKeyboard()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.keyList = QtWidgets.QListView(self.centralwidget)
        self.keyList.setGeometry(QtCore.QRect(260, 160, 256, 192))
        self.keyList.setObjectName("keyList")

        self.model = QtGui.QStandardItemModel()
        self.keyList.setModel(self.model)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    watcher = Keystroke_Watcher(ui)
    #PumpMessages()

    sys.exit(app.exec_())
